#环境配置
test_environment:
  domain: https://ws-test.vchangyi.com
  headers:
    "Content-Type": "application/json"
    "auth-token": "eyJpdiI6IjU0dVZxVFVCKzZOdkl6REhcL2NlSFZRPT0iLCJ2YWx1ZSI6IjJFZGhTeSsrZVcwOVhKS2FXczdPR1RcLzJIcG5pRnFGbW1kU0VVSHBzQmpKckxrRWVoN3FlamNaTmZXckExdCtUS0tuaWRrSjNcL2hiU2dVTkxWYVhMQ0Jmd0E1Y2NzeGE0N05VNWRvSk9wbmtUbm5rQks1N3cyTk5uajZrNnFBZStOQkZISElHR1hZbWNJYWF0NDBETVJ6dFlaOFVHd0xTK0JyWHNBSnJnXC8xZjhvcEU2K1Iycmc3cloyUEI3REpONTNKZDFcL2gwTFhCMDV0Z1pNcjNmU2tNVU9WXC9BT05NNXpkd3M4SERrenRDXC9kbGZUb1paS2ZCck5ydTJCQXN3V0ZFVnRRdG9rRlVsbmp4ZHRmZ2pSNW9mNFNOMWVUMGlJeldRWFd6UmVSNVl3PSIsIm1hYyI6Ijk3YzA3NWZlZGU2MzY4M2FlNmViYjViYzE4ZTc5MGZkNTUwMmVlNGZjNzE4ZjdkNWYzNThhZmM2YjVmZTA1NmQifQ=="

uat_environment:
  domain: https://ws-test.vchangyi.com
  headers:
    "Content-Type": "application/json"
    "auth-token": "eyJpdiI6IkM5UEhKMVJFN25MdnJ5dnNZZFNcL3JnPT0iLCJ2YWx1ZSI6IllcL3QwcktHTmhJNDdkYlwvd1hlMVJnQm9oK3dNekZwUm1Zc0oxYjFKcnh2bnNLM0dxYzBxcURqVThnN2ZlZ1lXQUNXWGMzN3ZEUHBjM0ZFYkJzTGtJVWlKd1NheDJCaVF3MjFvZm5sUis0UkR1dlc2aG1tMW5GbDVyalZsRklUTjVHQ3hHYjZkdWxZclJWa0toRU8yek1hN2Z1dVgwQ3Y4TGV3cWh5WUpXektxdEFXWEpaYWQ0dVU4bmRkVFRoMFRNcEl2RXRcL2RTSEo3M1Q3ZlBOeEwwWDlFREZVenZuTWlZVHFEYk04emg2MkJTV3YrdFlxNlJuUWdtcmtaYUlqTGNkWEVGNFlSV1l2VXR4d28wclwvRStDQndrOER3dDM4Wm11Rkx1K2NpbFZhRT0iLCJtYWMiOiIwYTQxN2U3NGVmZDlkOGNlOTgxMjUwOWQyYjQ5ZTA2OTg0YjU0OTNlZmEyMTdlMWQzM2M2MGQ3ZDE4ZTc5YmMzIn0="

prod_environment:
  domain: https://ws-test.vchangyi.com
  headers:
    "Content-Type": "application/json"
    "auth-token": "eyJpdiI6IkM5UEhKMVJFN25MdnJ5dnNZZFNcL3JnPT0iLCJ2YWx1ZSI6IllcL3QwcktHTmhJNDdkYlwvd1hlMVJnQm9oK3dNekZwUm1Zc0oxYjFKcnh2bnNLM0dxYzBxcURqVThnN2ZlZ1lXQUNXWGMzN3ZEUHBjM0ZFYkJzTGtJVWlKd1NheDJCaVF3MjFvZm5sUis0UkR1dlc2aG1tMW5GbDVyalZsRklUTjVHQ3hHYjZkdWxZclJWa0toRU8yek1hN2Z1dVgwQ3Y4TGV3cWh5WUpXektxdEFXWEpaYWQ0dVU4bmRkVFRoMFRNcEl2RXRcL2RTSEo3M1Q3ZlBOeEwwWDlFREZVenZuTWlZVHFEYk04emg2MkJTV3YrdFlxNlJuUWdtcmtaYUlqTGNkWEVGNFlSV1l2VXR4d28wclwvRStDQndrOER3dDM4Wm11Rkx1K2NpbFZhRT0iLCJtYWMiOiIwYTQxN2U3NGVmZDlkOGNlOTgxMjUwOWQyYjQ5ZTA2OTg0YjU0OTNlZmEyMTdlMWQzM2M2MGQ3ZDE4ZTc5YmMzIn0="
